config/routes.rb
Rails.application.routes.draw do
  
  resources :posts

  devise_for :usuarios, controllers: {omniauth_callbacks: "omniauth_callbacks", 
                                      registrations: "registrations"}
  get 'welcome/index'

  root 'welcome#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :usuario
  validates :titulo, presence: true, uniqueness: true
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook, :twitter]

  def email_required?
    false
  end

#=begin
  validates :username, presence: true, uniqueness: true, 
  					length: {in: 5..20, too_short: "Tiene que tener al menos 5 caracteres", too_long: "Máximo 20 caracteres"},
  					format: {with: /([A-Za-z0-9\-\_]+)/, message: "Username puede sólo contener letras, números y guiones"}
#=end

 #validate :validacion_personalizada, on: :create

  def self.find_or_create_by_omniauth(auth)
  	usuario = Usuario.where(provider: auth[:provider], uid: auth[:uid]).first

  	unless usuario
  		usuario = Usuario.create(
  			nombre: auth[:nombre],
  			apellido: auth[:apellido],
  			username: auth[:username],
  			email: "",
  			uid: auth[:uid],
  			provider: auth[:provider],
  			password: Devise.friendly_token[0,20]
  		)
  	end
    usuario  	
  end
=begin  
  private
  def validacion_personalizada
  	if true

  	else
  		errors.add(:username, "Tu username no es valido")
  	end
  end
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
	def facebook
		auth 	= request.env["omniauth.auth"]
		#raise auth.to_yaml
		data	= {
			nombre: auth.info.first_name,
			apellido: auth.info.last_name,
			username: auth.info.nickname,
			email: auth.info.email,
			provider: auth.provider,
			uid: auth.uid
		}

		@usuario = Usuario.find_or_create_by_omniauth(data)

		if @usuario.persisted?
			sign_in_and_redirect @usuario, event: :authentication
		else
			session[:omniauth_errors] = @usuario.errors.full_messages.to_sentence unless @usuario.save  #(if not @usuario.save)

			session[:omniauth_data] = data

			redirect_to new_usuario_registration_url
		end
	end
	def twitter
				auth 	= request.env["omniauth.auth"]
		#raise auth.to_yaml
		data	= {
			nombre: auth.info.name,
			apellido: "",
			username: auth.info.nickname,
			email: "",
			provider: auth.provider,
			uid: auth.uid
		}

		@usuario = Usuario.find_or_create_by_omniauth(data)

		if @usuario.persisted?
			sign_in_and_redirect @usuario, event: :authentication
		else
			session[:omniauth_errors] = @usuario.errors.full_messages.to_sentence unless @usuario.save  #(if not @usuario.save)

			session[:omniauth_data] = data

			redirect_to new_usuario_registration_url
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:titulo, :contenido, :extension, :usuario_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
			super
	end
	def create
			super
	end
	def update
			super
	end

	private
	def sign_up_params
		allow = [:email, :username, :password, :password_confirmation]
		params.require(resource_name).permit(allow)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_email_oauth
		if session[:omniauth_data]
			session[:omniauth_data][:email]
		else
			""
		end
	end
	def get_username_oauth
		if session[:omniauth_data]
			session[:omniauth_data][:username]
		else
			""
		end
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyDesign</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <p class="notice" style"<%= "display:none;" if notice.nil? %>"><%= notice %></p>
 <p class="alert" <%= "display:none;" if alert.nil? %>"><%= alert %></p>
 <header>
 	<nav>
 		<ul class="nav nav-tabs">
 			<li>
 				<%= link_to "Inicio", root_path %>
 			</li>
 			<% if usuario_signed_in? %>
 				<li>
 					<%= link_to "Editar Perfil", edit_usuario_registration_path(current_usuario) %>
 				</li>
 				<li>
 					<%= button_to "Cerrar sesión", destroy_usuario_session_path, method: :delete, class:"btn-logout" %>	
 				</li>
 			<%else%>
				<li>
					<%= link_to "Ingresar", new_usuario_session_path %>	
				</li>
				<li>
					<%= link_to "Registrarse", new_usuario_registration_path %>	
				</li>
 			<%end%>
 		</ul> 		
 	</nav> 	
 </header>
	<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </div>
  <div class="field">
    <%= f.label :extension %><br>
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.text_field :usuario_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th>Extension</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.titulo %></td>
        <td><%= post.contenido %></td>
        <td><%= post.extension %></td>
        <td><%= post.usuario %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @post.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @post.contenido %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @post.extension %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @post.usuario %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello stranger!</h1>
<p>Find me in app/views/welcome/index.html.erb</p>